In [1]:
import numpy as np

In [11]:
a = [
    [
        [
            k+j*3+i*9 for k in range(3)
        ] for j in range(3)
    ] for i in range(3)
]

num = 30
for i in a:
    for j in i:
        for k in i:
            k.append(num)
            num += 1
        break
a

In [21]:
scalar = 5.679
vector = np.array([3, 4,5 , 6])
matrix = np.array(
    [
        [
            (j + i * 2) + 1 for j in range(2)
        ] for i in range(3)
    ]
)
tensor = np.array(a)

In [23]:
matrix.T

array([[1, 3, 5],
       [2, 4, 6]])

In [24]:
vector.T

array([3, 4, 5, 6])

In [25]:
tensor.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[30, 33, 36],
        [31, 34, 37],
        [32, 35, 38]]])

In [26]:
matrix.T.T

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
matrix + matrix

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [28]:
matrix + matrix.T

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [29]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([[6, 5], [4, 3], [2, 1]])
z = x+y
z

array([[7, 7],
       [7, 7],
       [7, 7]])

In [30]:
matrix + scalar

array([[ 6.679,  7.679],
       [ 8.679,  9.679],
       [10.679, 11.679]])

In [33]:
a = [
    [
        (j + i * 5) + 1 for j in range(5)
    ] for i in range(5)
]

In [34]:
a = np.array(a)

In [35]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
a + a.T

array([[ 2,  8, 14, 20, 26],
       [ 8, 14, 20, 26, 32],
       [14, 20, 26, 32, 38],
       [20, 26, 32, 38, 44],
       [26, 32, 38, 44, 50]])