In [1]:
import numpy as np

In [2]:
scalar = 5.679
vector = np.array([3, 4,5 ])
matrix = np.array([[1, 2], [3, 4], [5, 6]])

In [4]:
vector + matrix.T

array([[ 4,  7, 10],
       [ 5,  8, 11]])

In [5]:
matrix + np.array([[42], [42], [42]])

array([[43, 44],
       [45, 46],
       [47, 48]])

In [6]:
matrix + 42

array([[43, 44],
       [45, 46],
       [47, 48]])